### PR TITLE
Remove swagger comments, update IETF, fix 404 error message, initial error handling clean up

### LINKED ISSUE #114: Remove comments for swagger doc generation (unused)
## Description:
- To clean up code, remove the swagger comments in controllers and model files to clean up code, since we have moved towards using a static file/shared swagger documentation. 

- References #15

### LINKED ISSUE #121: webv validation error
## Description
- The following webv errors when running the new bad.json file

/api/actors/nm12345
  ContentType: application/json Expected: text/plain
  ExactMatch: Actual : "Error: Cosmos Error: 404" : Expected: Actor Not Found

/api/movies/tt12345
  ContentType: application/json Expected: text/plain
  ExactMatch: Actual : "Error: Cosmos Error: 404" : Expected: Movie Not Found

## Expected Behavior
- A clear and concise description of what you expected to happen.

## Reproduce
- run webv with newbad.json

### PR DESCRIPTION
**Pull request by aflinchb**
## Type of PR

- [ ] Documentation changes
- [x] Code changes
- [ ] Test changes
- [ ] CI-CD changes
- [ ] GitHub Template changes

## Purpose of PR
- Remove unused swagger comments for auto generated docs
- Update IETF health check response with new updates to IETF spec
- Fix response for 404 not found when doing a direct read by actorId and movieId
- Includes initial changes to fix overall approach to error handling
    - Removes try/catch from CosmosDBService so error handling is bubbled up to controller
    - Improves error handling in Controllers
    - TODO's in code and further work for error handling across the app will be resolved by Tobias's work in https://github.com/retaildevcrews/helium/issues/300

## Review notes
- Current version of code is running at https://anflinch.azurewebsites.net to test

## Issues Closed or Referenced

- Closes #114 
- Closes #121 
- References https://github.com/retaildevcrews/helium/issues/197
- References https://github.com/retaildevcrews/helium/issues/300

### CODE REVIEW

File: src/controllers/GenreController.ts [hunk 1]
```diff
@@ -17,34 +17,24 @@ export class GenreController implements interfaces.Controller {
...
   @Get("/")
   public async getAllGenres(req: Request, res) {
     let resCode: number = HttpStatus.OK;
     let results: string[];
+
     try {
       results = await this.cosmosDb.queryDocuments(sqlGenres);
     } catch (err) {
-      resCode = HttpStatus.INTERNAL_SERVER_ERROR;
+      // TODO: Refactor error handling/response/logging to reduce duplication
```
Comment (bartr) [inline src/controllers/GenreController.ts]: I made this a helper function in C# and it cut a lot of duplicate code out. Should consider for future PRs (if not already)

Comment (aflinchb) [reply src/controllers/GenreController.ts]: Definitely - Tobias and I briefly went over using a similar approach and he's going to look into it with the follow up issue/task
